services:
  db:
    image: postgres:14
    container_name: devquest-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - devquest-data:/var/lib/postgresql/data
    networks:
      - devquest-network

  api:
    container_name: devquest-api
    image: maven:3.9.9-eclipse-temurin-21
    working_dir: /api
    volumes:
      - .:/api
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_AI_OPENAI_API_KEY: ${SPRING_AI_OPENAI_API_KEY}
    command: ["./mvnw", "spring-boot:run"]
    networks:
      - devquest-network

volumes:
  devquest-data:

networks:
  devquest-network:
    driver: bridge