spring:
  application:
    name: api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
      exclude: static/**,public/**
dotenv:
  enabled: true
  systemProperties: true